title: Smart Image Suite
description: Client-Side Batch Image Compressor and Dimension Resizer
theme: jekyll-theme-merlot # Aap koi bhi default theme chun sakte hain, hum layout null use kar rahe hain
